<option value="Abhyudaya Co-op. Bank Ltd." >Abhyudaya Co-op. Bank Ltd.</option>
<option value="Abn Amro Bank" >Abn Amro Bank</option>
<option value="Abn Amro Bank N.V." >Abn Amro Bank N.V.</option>
<option value="Abu Dhabi Commercial Bank Ltd." >Abu Dhabi Commercial Bank Ltd.</option>
<option value="Agricultural Finance Corporation Ltd." >Agricultural Finance Corporation Ltd.</option>
<option value="Ahmedabad City & Dist. Co-op. Banks Association" >Ahmedabad City & Dist. Co-op. Banks Association</option>
<option value="Air Corporations Employees Co-op. Bank Ltd." >Air Corporations Employees Co-op. Bank Ltd.</option>
<option value="Allahabad Bank" >Allahabad Bank</option>
<option value="Allahabad District Co-operative Bank Ltd." >Allahabad District Co-operative Bank Ltd.</option>
<option value="Allahabad Kshetriya Gramin Bank" >Allahabad Kshetriya Gramin Bank</option>
<option value="Amanath Co-op. Bank Ltd." >Amanath Co-op. Bank Ltd.</option>
<option value="American Express Bank Ltd." >American Express Bank Ltd.</option>
<option value="Andhra Bank" >Andhra Bank</option>
<option value="Andhra Pragati Bank" >Andhra Pragati Bank</option>
<option value="Apna Sahakari Bank Ltd." >Apna Sahakari Bank Ltd.</option>
<option value="Arab Bangladesh Bank Limited" >Arab Bangladesh Bank Limited</option>
<option value="Asset Reconstruction Company (India) Limited" >Asset Reconstruction Company (India) Limited</option>
<option value="AXIS BANK LTD." >AXIS BANK LTD.</option>
<option value="Bank Internasional Indonesia" >Bank Internasional Indonesia</option>
<option value="bank muscat" >bank muscat</option>
<option value="Bank of America N.A." >Bank of America N.A.</option>
<option value="Bank of Bahrain & Kuwait BSC" >Bank of Bahrain & Kuwait BSC</option>
<option value="Bank of Baroda" >Bank of Baroda</option>
<option value="Bank of India" >Bank of India</option>
<option value="Bank of Maharashtra" >Bank of Maharashtra</option>
<option value="Bank of Punjab" >Bank of Punjab</option>
<option value="Bankersindia" >Bankersindia</option>
<option value="Barclays Bank Plc" >Barclays Bank Plc</option>
<option value="Baroda Eastern Uttar Pradesh Gramin Bank" >Baroda Eastern Uttar Pradesh Gramin Bank</option>
<option value="Bassein Catholic Co-op. Bank Ltd." >Bassein Catholic Co-op. Bank Ltd.</option>
<option value="Bharat Overseas Bank Ltd." >Bharat Overseas Bank Ltd.</option>
<option value="Bnp Paribas" >Bnp Paribas</option>
<option value="Bombay Mercantile Co-op. Bank Ltd." >Bombay Mercantile Co-op. Bank Ltd.</option>
<option value="Calyon Bank" >Calyon Bank</option>
<option value="Canara Bank" >Canara Bank</option>
<option value="Central Bank of India" >Central Bank of India</option>
<option value="Centurion Bank of Punjab Limited" >Centurion Bank of Punjab Limited</option>
<option value="Citibank India" >Citibank India</option>
<option value="Citibank N.A." >Citibank N.A.</option>
<option value="Citizencredit Co-Op. Bank Ltd." >Citizencredit Co-Op. Bank Ltd.</option>
<option value="City Union Bank Ltd." >City Union Bank Ltd.</option>
<option value="Coastal Local Area Bank Ltd." >Coastal Local Area Bank Ltd.</option>
<option value="Corporation Bank" >Corporation Bank</option>
<option value="Cosmos Co-Operative Bank" >Cosmos Co-Operative Bank</option>
<option value="Credit Information Bureau (India) Limited" >Credit Information Bureau (India) Limited</option>
<option value="Dena Bank" >Dena Bank</option>
<option value="Deutsche Bank AG" >Deutsche Bank AG</option>
<option value="Development Credit Bank Ltd." >Development Credit Bank Ltd.</option>
<option value="Dewan Housing Finance Corporation Ltd." >Dewan Housing Finance Corporation Ltd.</option>
<option value="Dombivli Nagari Sahakari Bank Ltd." >Dombivli Nagari Sahakari Bank Ltd.</option>
<option value="Excellent Co-operative Bank Ltd., Mumbai" >Excellent Co-operative Bank Ltd., Mumbai</option>
<option value="Export-Import Bank of India" >Export-Import Bank of India</option>
<option value="Federal Bank" >Federal Bank</option>
<option value="Global Trust Bank Limited" >Global Trust Bank Limited</option>
<option value="Guardian Sahakara Bank Niyamita" >Guardian Sahakara Bank Niyamita</option>
<option value="HDFC Bank Ltd." >HDFC Bank Ltd.</option>
<option value="ICICI Bank Limited" >ICICI Bank Limited</option>
<option value="IDBI Bank Limited" >IDBI Bank Limited</option>
<option value="Indian Bank" >Indian Bank</option>
<option value="Indian Overseas Bank" >Indian Overseas Bank</option>
<option value="IndusInd Bank Limited" >IndusInd Bank Limited</option>
<option value="Industrial Development Bank of India (IDBI)" >Industrial Development Bank of India (IDBI)</option>
<option value="Infrastructure Leasing & Financial Service Limited" >Infrastructure Leasing & Financial Service Limited</option>
<option value="ING Vysya Bank Ltd." >ING Vysya Bank Ltd.</option>
<option value="J P Morgan Chase Bank, National Association" >J P Morgan Chase Bank, National Association</option>
<option value="Jalgaon Janata Sahakari Bank Ltd." >Jalgaon Janata Sahakari Bank Ltd.</option>
<option value="Jammu and Kashmir Bank" >Jammu and Kashmir Bank</option>
<option value="Janakalyan Sahakari Bank Ltd." >Janakalyan Sahakari Bank Ltd.</option>
<option value="Janalaxmi Co-op Bank Ltd." >Janalaxmi Co-op Bank Ltd.</option>
<option value="Janata Sahakari Bank Ltd." >Janata Sahakari Bank Ltd.</option>
<option value="Karnataka Bank Ltd." >Karnataka Bank Ltd.</option>
<option value="Kolhapur Zilla Nagari Banks Sahakari Association Ltd." >Kolhapur Zilla Nagari Banks Sahakari Association Ltd.</option>
<option value="Kotak Mahindra Bank Limited" >Kotak Mahindra Bank Limited</option>
<option value="Krung Thai Bank Public Company Limited" >Krung Thai Bank Public Company Limited</option>
<option value="Lord Krishna Bank Ltd." >Lord Krishna Bank Ltd.</option>
<option value="Mashreqbank psc" >Mashreqbank psc</option>
<option value="MasterCard International Inc" >MasterCard International Inc</option>
<option value="Mizuho Corporate Bank Ltd." >Mizuho Corporate Bank Ltd.</option>
<option value="National Housing Bank" >National Housing Bank</option>
<option value="Nedungadi Bank" >Nedungadi Bank</option>
<option value="New India Co-op. Bank Ltd." >New India Co-op. Bank Ltd.</option>
<option value="Nutan Nagarik Sahakari Bank Ltd." >Nutan Nagarik Sahakari Bank Ltd.</option>
<option value="Oman International Bank S A O G" >Oman International Bank S A O G</option>
<option value="Oriental Bank of Commerce" >Oriental Bank of Commerce</option>
<option value="Ottapalam Co-operative Urban Bank Ltd." >Ottapalam Co-operative Urban Bank Ltd.</option>
<option value="Pali Urban Co-op. Bank Ltd." >Pali Urban Co-op. Bank Ltd.</option>
<option value="Pune District Central Co-op. Bank Ltd." >Pune District Central Co-op. Bank Ltd.</option>
<option value="Punjab & Maharashtra Co-op. Bank Ltd." >Punjab & Maharashtra Co-op. Bank Ltd.</option>
<option value="Punjab & Sind Bank" >Punjab & Sind Bank</option>
<option value="Punjab National Bank" selected>Punjab National Bank</option>
<option value="Rajkot Nagarik Sahakari Bank Ltd." >Rajkot Nagarik Sahakari Bank Ltd.</option>
<option value="Reserve Bank of India" >Reserve Bank of India</option>
<option value="Riyad Bank" >Riyad Bank</option>
<option value="Rupee Co-op. Bank Ltd." >Rupee Co-op. Bank Ltd.</option>
<option value="Saraswat Co-operative Bank" >Saraswat Co-operative Bank</option>
<option value="SBI Commercial and International Bank Ltd." >SBI Commercial and International Bank Ltd.</option>
<option value="Shri Arihant Co-op. Bank Limited." >Shri Arihant Co-op. Bank Limited.</option>
<option value="Small Farmers Agri-Business Consortium (SFAC)" >Small Farmers Agri-Business Consortium (SFAC)</option>
<option value="Societe Generale" >Societe Generale</option>
<option value="Sonali Bank" >Sonali Bank</option>
<option value="South Indian Bank" >South Indian Bank</option>
<option value="Sree Narayana Guru Co-op. Bank Ltd." >Sree Narayana Guru Co-op. Bank Ltd.</option>
<option value="Standard Chartered Bank" >Standard Chartered Bank</option>
<option value="State Bank of Bikaner and Jaipur" >State Bank of Bikaner and Jaipur</option>
<option value="State Bank of Hyderabad" >State Bank of Hyderabad</option>
<option value="State Bank of India" >State Bank of India</option>
<option value="State Bank of Indore" >State Bank of Indore</option>
<option value="State Bank of Mauritius Ltd." >State Bank of Mauritius Ltd.</option>
<option value="State Bank of Mysore" >State Bank of Mysore</option>
<option value="State Bank Of Patiala" >State Bank Of Patiala</option>
<option value="State Bank Of Saurashtra" >State Bank Of Saurashtra</option>
<option value="State Bank of Travancore" >State Bank of Travancore</option>
<option value="Syndicate Bank" >Syndicate Bank</option>
<option value="Tamilnad Mercantile Bank Ltd." >Tamilnad Mercantile Bank Ltd.</option>
<option value="Textile Traders Cooperative Bank" >Textile Traders Cooperative Bank</option>
<option value="Thane Janata Sahakari Bank" >Thane Janata Sahakari Bank</option>
<option value="The A.P. Mahesh Co-op. Urban Bank Ltd." >The A.P. Mahesh Co-op. Urban Bank Ltd.</option>
<option value="The Andhra Pradesh State Co-op. Bank Ltd." >The Andhra Pradesh State Co-op. Bank Ltd.</option>
<option value="The Bank of Nova Scotia" >The Bank of Nova Scotia</option>
<option value="The Bank of Rajasthan Limited" >The Bank of Rajasthan Limited</option>
<option value="The Bank of Tokyo-Mitsubishi, Ltd." >The Bank of Tokyo-Mitsubishi, Ltd.</option>
<option value="The Belgaum District Central Co-op. Bank Ltd." >The Belgaum District Central Co-op. Bank Ltd.</option>
<option value="The Bharat Co-op. Bank (Mumbai) Ltd." >The Bharat Co-op. Bank (Mumbai) Ltd.</option>
<option value="The Catholic Syrian Bank Ltd" >The Catholic Syrian Bank Ltd</option>
<option value="The Cosmos Co-op. Bank Ltd." >The Cosmos Co-op. Bank Ltd.</option>
<option value="The Deccan Merchants Co-op. Bank Ltd." >The Deccan Merchants Co-op. Bank Ltd.</option>
<option value="The Development Bank of Singapore Ltd." >The Development Bank of Singapore Ltd.</option>
<option value="The Dhanalakshmi Bank Limited." >The Dhanalakshmi Bank Limited.</option>
<option value="The Federal Bank Ltd." >The Federal Bank Ltd.</option>
<option value="The Ganesh Bank of Kurundwad Ltd." >The Ganesh Bank of Kurundwad Ltd.</option>
<option value="The Greater Bombay Co-op. Bank Ltd." >The Greater Bombay Co-op. Bank Ltd.</option>
<option value="The Gujarat Industrial Co-op. Bank Ltd." >The Gujarat Industrial Co-op. Bank Ltd.</option>
<option value="The HDFC Bank Ltd." >The HDFC Bank Ltd.</option>
<option value="The Hongkong & Shanghai Banking Corporation Ltd." >The Hongkong & Shanghai Banking Corporation Ltd.</option>
<option value="The Jalgaon Peoples Co-op. Bank Ltd." >The Jalgaon Peoples Co-op. Bank Ltd.</option>
<option value="The Jammu & Kashmir Bank Ltd." >The Jammu & Kashmir Bank Ltd.</option>
<option value="The Kalupur Commercial Co-op. Bank Limited" >The Kalupur Commercial Co-op. Bank Limited</option>
<option value="The Kapol Co-op. Bank Ltd." >The Kapol Co-op. Bank Ltd.</option>
<option value="The Karad Urban Co-op. Bank Ltd." >The Karad Urban Co-op. Bank Ltd.</option>
<option value="The Karnataka State Co-op. Apex Bank Ltd." >The Karnataka State Co-op. Apex Bank Ltd.</option>
<option value="The Karur Vysya Bank Ltd." >The Karur Vysya Bank Ltd.</option>
<option value="The Lakshmi Vilas Bank Ltd." >The Lakshmi Vilas Bank Ltd.</option>
<option value="The Mahanagar Co-op. Bank Ltd." >The Mahanagar Co-op. Bank Ltd.</option>
<option value="The Municipal Co-op. Bank Ltd." >The Municipal Co-op. Bank Ltd.</option>
<option value="The Nainital Bank Ltd." >The Nainital Bank Ltd.</option>
<option value="The North Kanara GSB Co-op. Bank Ltd." >The North Kanara GSB Co-op. Bank Ltd.</option>
<option value="The Orissa State Co-op. Bank Limited" >The Orissa State Co-op. Bank Limited</option>
<option value="The Radhasoami Urban Co-op. Bank Ltd." >The Radhasoami Urban Co-op. Bank Ltd.</option>
<option value="The Ratnakar Bank Ltd." >The Ratnakar Bank Ltd.</option>
<option value="The Sangli Bank Ltd." >The Sangli Bank Ltd.</option>
<option value="The Saraswat Co-op. Bank Ltd." >The Saraswat Co-op. Bank Ltd.</option>
<option value="The Shamrao Vithal Co-op. Bank Ltd." >The Shamrao Vithal Co-op. Bank Ltd.</option>
<option value="The South Indian Bank Ltd." >The South Indian Bank Ltd.</option>
<option value="The South Indian Co-op. Bank Ltd." >The South Indian Co-op. Bank Ltd.</option>
<option value="The Surat Peoples Co-op. Bank Ltd." >The Surat Peoples Co-op. Bank Ltd.</option>
<option value="The Tamil Nadu State Apex Co-op. Bank Ltd." >The Tamil Nadu State Apex Co-op. Bank Ltd.</option>
<option value="The Thane District Central Co-op. Bank Ltd." >The Thane District Central Co-op. Bank Ltd.</option>
<option value="The Thane Janata Sahakari Bank Ltd." >The Thane Janata Sahakari Bank Ltd.</option>
<option value="The United Western Bank Ltd." >The United Western Bank Ltd.</option>
<option value="The Urban Co-op. Bank Ltd." >The Urban Co-op. Bank Ltd.</option>
<option value="The Zoroastrian Co-operative Bank Limited" >The Zoroastrian Co-operative Bank Limited</option>
<option value="UCO Bank" >UCO Bank</option>
<option value="Union Bank of India" >Union Bank of India</option>
<option value="United Bank of India" >United Bank of India</option>
<option value="UP Co-Operative Bank Ltd." >UP Co-Operative Bank Ltd.</option>
<option value="UTI Bank Ltd." >UTI Bank Ltd.</option>
<option value="Vaidyanath Bank" >Vaidyanath Bank</option>
<option value="Vijaya Bank" >Vijaya Bank</option>
<option value="Vysya Bank" >Vysya Bank</option>
<option value="Yes Bank Limited" >Yes Bank Limited</option>
<option value="Youth Development Co-op. Bank Ltd." >Youth Development Co-op. Bank Ltd.</option>